import { useCallback, useEffect, useState } from 'react';
import { Check, ExternalLink, Radar, X } from 'lucide-react';
import { Modal } from '../../components/ui/Modal';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../lib/auth';
import { useToast } from '../../lib/toast';

interface Candidate { id:string; ikn:string; title:string; institution:string; city:string|null; deadline_at:string; matched_keyword:string }

export function EkapCandidates({canWrite,onAccepted}:{canWrite:boolean;onAccepted:()=>Promise<void>}){
  const {user}=useAuth(); const {notify}=useToast(); const [open,setOpen]=useState(false); const [items,setItems]=useState<Candidate[]>([]); const [loading,setLoading]=useState(false);
  const refresh=useCallback(async()=>{if(!user?.organizationId)return;setLoading(true);const{data,error}=await supabase.from('ekap_candidates').select('id,ikn,title,institution,city,deadline_at,matched_keyword').eq('organization_id',user.organizationId).eq('status','bekliyor').order('deadline_at');if(!error)setItems((data??[]) as Candidate[]);setLoading(false)},[user?.organizationId]);
  useEffect(()=>{void refresh()},[refresh]);
  const review=async(item:Candidate,accept:boolean)=>{if(!user?.organizationId||!user.id)return;if(accept){const{error}=await supabase.from('tenders').insert({organization_id:user.organizationId,tender_number:item.ikn,title:item.title,institution:item.institution,tender_type:'mal',method:'acik',status:'hazirlaniyor',estimated_amount:0,currency:'TRY',deadline_at:item.deadline_at,assigned_to:'',description:`EKAP 4734 kapsamı · Eşleşme: ${item.matched_keyword}`});if(error&&error.code!=='23505'){notify(error.message,'error');return}}const{error}=await supabase.from('ekap_candidates').update({status:accept?'onaylandi':'reddedildi',reviewed_at:new Date().toISOString(),reviewed_by:user.id}).eq('id',item.id).eq('organization_id',user.organizationId);if(error){notify(error.message,'error');return}notify(accept?'İhale onaylandı ve takvime eklendi.':'Aday reddedildi.','success');await refresh();if(accept)await onAccepted()};
  return <><button className="btn-secondary" onClick={()=>{setOpen(true);void refresh()}}><Radar size={16}/>EKAP’tan Bulunanlar{items.length?` (${items.length})`:''}</button><Modal open={open} onClose={()=>setOpen(false)} title="EKAP’tan Bulunanlar" size="lg"><div className="mb-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-800">4734 kapsamında kırmızı et ve et ürünleriyle eşleşen kayıtlar. Onaylanan ihale İhaleler listesine ve Takvim’e eklenir.</div>{loading?<div className="py-10 text-center text-gray-400">Kayıtlar yükleniyor...</div>:items.length===0?<div className="py-10 text-center text-gray-400">Onay bekleyen EKAP kaydı yok.</div>:<div className="max-h-[60vh] space-y-3 overflow-y-auto">{items.map(x=><div key={x.id} className="rounded-xl border border-gray-200 p-4"><div className="flex items-start justify-between gap-4"><div><div className="mb-1 text-xs font-medium text-brand-600">{x.ikn} · {x.matched_keyword}</div><div className="font-medium text-gray-900">{x.title}</div><div className="mt-1 text-sm text-gray-500">{x.institution} · {x.city||'—'} · {new Date(x.deadline_at).toLocaleString('tr-TR',{dateStyle:'short',timeStyle:'short'})}</div></div>{canWrite&&<div className="flex shrink-0 gap-2"><button className="btn-secondary px-3" onClick={()=>void review(x,false)} title="Reddet"><X size={16}/></button><button className="btn-primary px-3" onClick={()=>void review(x,true)} title="Onayla"><Check size={16}/>Onayla</button></div>}</div><a href="https://ekapv2.kik.gov.tr/ekap/search" target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs text-brand-600 hover:underline">EKAP’ta doğrula <ExternalLink size={12}/></a></div>)}</div>}</Modal></>
}
