import { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarClock, CircleDollarSign, Gavel, Pencil, Plus, Search, Trash2, Trophy } from 'lucide-react';
import { PageHeader } from '../../components/ui/PageHeader';
import { Modal } from '../../components/ui/Modal';
import { ModuleFileActions } from '../../components/ui/ModuleFileActions';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../lib/auth';
import { useToast } from '../../lib/toast';
import { TenderFileManager } from './TenderFileManager';
import { EkapCandidates } from './EkapCandidates';

type TenderStatus = 'hazirlaniyor'|'teklif-verildi'|'degerlendirme'|'kazanildi'|'kaybedildi'|'iptal';
interface Tender { id:string; tender_number:string; title:string; institution:string; tender_type:string; method:string; status:TenderStatus; estimated_amount:number; bid_amount:number|null; currency:string; publication_date:string|null; deadline_at:string; result_date:string|null; assigned_to:string; description:string|null }
interface FormState { tenderNumber:string; title:string; institution:string; tenderType:string; method:string; status:TenderStatus; estimatedAmount:string; bidAmount:string; currency:string; publicationDate:string; deadlineAt:string; resultDate:string; assignedTo:string; description:string }
const emptyForm=():FormState=>({tenderNumber:'',title:'',institution:'',tenderType:'hizmet',method:'acik',status:'hazirlaniyor',estimatedAmount:'',bidAmount:'',currency:'TRY',publicationDate:'',deadlineAt:'',resultDate:'',assignedTo:'',description:''});
const statusLabels:Record<TenderStatus,string>={hazirlaniyor:'Hazırlanıyor','teklif-verildi':'Teklif Verildi',degerlendirme:'Değerlendirme',kazanildi:'Kazanıldı',kaybedildi:'Kaybedildi',iptal:'İptal'};
const statusCls:Record<TenderStatus,string>={hazirlaniyor:'bg-gray-100 text-gray-600','teklif-verildi':'bg-blue-50 text-blue-700',degerlendirme:'bg-amber-50 text-amber-700',kazanildi:'bg-emerald-50 text-emerald-700',kaybedildi:'bg-red-50 text-red-700',iptal:'bg-gray-100 text-gray-500'};
const money=(n:number,c='TRY')=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:c,maximumFractionDigits:0}).format(n);

export function TendersPage(){
  const {user}=useAuth(); const {notify}=useToast(); const [items,setItems]=useState<Tender[]>([]); const [loading,setLoading]=useState(true);
  const [query,setQuery]=useState(''); const [filter,setFilter]=useState(''); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Tender>(); const [form,setForm]=useState<FormState>(emptyForm()); const [saving,setSaving]=useState(false);
  const canWrite=['Yönetici','Muhasebe','Finans'].includes(user?.role??'');
  const refresh=useCallback(async()=>{if(!user?.organizationId)return;setLoading(true);const{data,error}=await supabase.from('tenders').select('*').eq('organization_id',user.organizationId).order('deadline_at',{ascending:true});if(error)notify(error.message,'error');else setItems((data??[]).map(r=>({...r,estimated_amount:Number(r.estimated_amount),bid_amount:r.bid_amount==null?null:Number(r.bid_amount)})) as Tender[]);setLoading(false)},[user?.organizationId,notify]);
  useEffect(()=>{void refresh()},[refresh]);
  const filtered=useMemo(()=>items.filter(x=>(!filter||x.status===filter)&&`${x.tender_number} ${x.title} ${x.institution} ${x.assigned_to}`.toLowerCase().includes(query.toLowerCase())),[items,query,filter]);
  const upcoming=items.filter(x=>!['kazanildi','kaybedildi','iptal'].includes(x.status)&&new Date(x.deadline_at)>=new Date()).length;
  const openForm=(item?:Tender)=>{setEditing(item);setForm(item?{tenderNumber:item.tender_number,title:item.title,institution:item.institution,tenderType:item.tender_type,method:item.method,status:item.status,estimatedAmount:String(item.estimated_amount),bidAmount:item.bid_amount==null?'':String(item.bid_amount),currency:item.currency,publicationDate:item.publication_date??'',deadlineAt:item.deadline_at.slice(0,16),resultDate:item.result_date??'',assignedTo:item.assigned_to,description:item.description??''}:emptyForm());setOpen(true)};
  const save=async()=>{if(!user?.organizationId||!form.tenderNumber.trim()||!form.title.trim()||!form.institution.trim()||!form.deadlineAt){notify('İhale no, başlık, kurum ve son teklif tarihi zorunludur.','error');return}setSaving(true);const payload={organization_id:user.organizationId,tender_number:form.tenderNumber.trim(),title:form.title.trim(),institution:form.institution.trim(),tender_type:form.tenderType,method:form.method,status:form.status,estimated_amount:Number(form.estimatedAmount)||0,bid_amount:form.bidAmount?Number(form.bidAmount):null,currency:form.currency,publication_date:form.publicationDate||null,deadline_at:new Date(form.deadlineAt).toISOString(),result_date:form.resultDate||null,assigned_to:form.assignedTo.trim(),description:form.description.trim()||null,updated_at:new Date().toISOString()};const q=editing?supabase.from('tenders').update(payload).eq('id',editing.id).eq('organization_id',user.organizationId):supabase.from('tenders').insert(payload);const{error}=await q;setSaving(false);if(error){notify(error.message,'error');return}notify(editing?'İhale güncellendi.':'İhale eklendi.','success');setOpen(false);await refresh()};
  const remove=async(item:Tender)=>{if(!confirm(`“${item.title}” ihalesi silinsin mi?`))return;const{error}=await supabase.from('tenders').delete().eq('id',item.id).eq('organization_id',user?.organizationId);if(error)notify(error.message,'error');else{notify('İhale silindi.','success');await refresh()}};
  return <div className="mx-auto max-w-7xl"><PageHeader title="İhaleler" description="İhale süreçlerini, teklif tarihlerini, sorumluları ve sonuçları yönetin." actions={<><EkapCandidates canWrite={canWrite} onAccepted={refresh}/><TenderFileManager tenders={items.map(x=>({id:x.id,title:x.title,tender_number:x.tender_number}))} canWrite={canWrite}/><ModuleFileActions module="tenders" exportName="ihaleler" uploadEnabled={false} rows={items.map(x=>({'İhale No':x.tender_number,Başlık:x.title,Kurum:x.institution,Tür:x.tender_type,Yöntem:x.method,Durum:statusLabels[x.status],'Yaklaşık Tutar':x.estimated_amount,'Teklif Tutarı':x.bid_amount,'Son Teklif':x.deadline_at,Sorumlu:x.assigned_to}))}/>{canWrite&&<button className="btn-primary" onClick={()=>openForm()}><Plus size={16}/>Yeni İhale</button>}</>}/>
    <div className="mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<Gavel size={17}/>} value={String(items.length)} label="Toplam İhale"/><Metric icon={<CalendarClock size={17}/>} value={String(upcoming)} label="Aktif / Yaklaşan"/><Metric icon={<Trophy size={17}/>} value={String(items.filter(x=>x.status==='kazanildi').length)} label="Kazanılan"/><Metric icon={<CircleDollarSign size={17}/>} value={money(items.reduce((s,x)=>s+(x.bid_amount??0),0))} label="Toplam Teklif"/></div>
    <div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="relative max-w-lg flex-1"><Search size={16} className="absolute left-3 top-3 text-gray-400"/><input className="input pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="İhale no, başlık, kurum veya sorumlu ara..."/></div><select className="input sm:w-52" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tüm Durumlar</option>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div>
    <div className="card overflow-x-auto"><table className="min-w-full"><thead><tr><th className="table-th">İhale</th><th className="table-th">Kurum</th><th className="table-th">Son Teklif</th><th className="table-th">Teklif Tutarı</th><th className="table-th">Sorumlu</th><th className="table-th">Durum</th><th className="table-th"></th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="table-td py-12 text-center text-gray-400">İhaleler yükleniyor...</td></tr>:filtered.length===0?<tr><td colSpan={7} className="table-td py-12 text-center text-gray-400">İhale bulunamadı.</td></tr>:filtered.map(x=><tr key={x.id} className="border-t border-gray-100"><td className="table-td"><div className="font-medium text-gray-900">{x.title}</div><div className="text-xs text-gray-500">{x.tender_number} · {x.tender_type}</div></td><td className="table-td">{x.institution}</td><td className="table-td">{new Date(x.deadline_at).toLocaleString('tr-TR',{dateStyle:'short',timeStyle:'short'})}</td><td className="table-td font-medium">{x.bid_amount==null?'—':money(x.bid_amount,x.currency)}</td><td className="table-td">{x.assigned_to||'—'}</td><td className="table-td"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusCls[x.status]}`}>{statusLabels[x.status]}</span></td><td className="table-td">{canWrite&&<div className="flex gap-2"><button className="text-gray-500 hover:text-brand-600" onClick={()=>openForm(x)} aria-label="Düzenle"><Pencil size={16}/></button><button className="text-gray-400 hover:text-red-600" onClick={()=>void remove(x)} aria-label="Sil"><Trash2 size={16}/></button></div>}</td></tr>)}</tbody></table></div>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?'İhaleyi Düzenle':'Yeni İhale'} size="lg"><div className="grid gap-4 sm:grid-cols-2"><Field label="İhale No"><input className="input" value={form.tenderNumber} onChange={e=>setForm({...form,tenderNumber:e.target.value})}/></Field><Field label="Başlık"><input className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Kurum"><input className="input" value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})}/></Field><Field label="Sorumlu"><input className="input" value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})}/></Field><Field label="İhale Türü"><select className="input" value={form.tenderType} onChange={e=>setForm({...form,tenderType:e.target.value})}><option value="mal">Mal Alımı</option><option value="hizmet">Hizmet</option><option value="yapim">Yapım</option><option value="danismanlik">Danışmanlık</option><option value="diger">Diğer</option></select></Field><Field label="Yöntem"><select className="input" value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option value="acik">Açık İhale</option><option value="pazarlik">Pazarlık</option><option value="dogrudan">Doğrudan Temin</option><option value="davet">Davet</option></select></Field><Field label="Durum"><select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value as TenderStatus})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Para Birimi"><select className="input" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>TRY</option><option>USD</option><option>EUR</option></select></Field><Field label="Yaklaşık Tutar"><input type="number" min="0" className="input" value={form.estimatedAmount} onChange={e=>setForm({...form,estimatedAmount:e.target.value})}/></Field><Field label="Teklif Tutarı"><input type="number" min="0" className="input" value={form.bidAmount} onChange={e=>setForm({...form,bidAmount:e.target.value})}/></Field><Field label="Yayın Tarihi"><input type="date" className="input" value={form.publicationDate} onChange={e=>setForm({...form,publicationDate:e.target.value})}/></Field><Field label="Son Teklif Tarihi"><input type="datetime-local" className="input" value={form.deadlineAt} onChange={e=>setForm({...form,deadlineAt:e.target.value})}/></Field><Field label="Sonuç Tarihi"><input type="date" className="input" value={form.resultDate} onChange={e=>setForm({...form,resultDate:e.target.value})}/></Field><Field label="Açıklama" wide><textarea className="input min-h-24" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><button className="btn-primary sm:col-span-2" disabled={saving} onClick={()=>void save()}>{saving?'Kaydediliyor...':'Kaydet'}</button></div></Modal>
  </div>
}
function Metric({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="card p-4"><div className="mb-3 flex h-8 w-8 items-center justify-center rounded-lg bg-gray-50 text-gray-500">{icon}</div><div className="text-xl font-semibold">{value}</div><div className="text-xs text-gray-500">{label}</div></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?'sm:col-span-2':''}><span className="label">{label}</span>{children}</label>}
