//
//  CektenViewModel.swift
//  dars-ios
//
//  Reactive @MainActor ViewModel orchestrating live Supabase data for CektenView.
//  Encapsulates live querying, tenor/cost calculation engines, status filtering,
//  and zero mock arrays.
//

import SwiftUI
import Combine
import Foundation

// MARK: - Cekten Service Protocol

/// Protocol defining backend data requirements for ÇEKTEN Hesabı.
public protocol CektenServiceProtocol: Sendable {
    func fetchCektenRecords() async throws -> [CektenHesap]
}

extension SupabaseService: CektenServiceProtocol {}

// MARK: - Status Filter Enum

/// Status filter pills matching Kuveyt Türk design tokens and prototype specifications.
public enum CektenStatusFilter: String, CaseIterable, Identifiable, Sendable {
    case all = "Tümü"
    case open = "Açık"
    case paid = "Ödendi"
    case partial = "Kısmi"
    
    public var id: String { rawValue }
    public var filterTitle: String { rawValue }
}

// MARK: - Date Filter Presets

/// Date range filter presets for ÇEKTEN records.
public enum CektenDateFilter: String, CaseIterable, Identifiable, Sendable {
    case all = "Tüm Tarihler"
    case thisMonth = "Bu Ay"
    case last30Days = "Son 30 Gün"
    case future30Days = "Gelecek 30 Gün"
    
    public var id: String { rawValue }
}

// MARK: - Calculation Simulation Result

/// Result payload generated by the interactive Trade Financing Cost Engine.
public struct CektenSimulationResult: Equatable, Sendable {
    public let principal: Double
    public let tenorDays: Int
    public let annualRate: Double
    public let commissionRate: Double
    public let financingCost: Double
    public let commissionAmount: Double
    public let totalDeductions: Double
    public let netProceeds: Double
    public let effectiveMonthlyRate: Double
    
    public init(
        principal: Double,
        tenorDays: Int,
        annualRate: Double,
        commissionRate: Double,
        financingCost: Double,
        commissionAmount: Double,
        totalDeductions: Double,
        netProceeds: Double,
        effectiveMonthlyRate: Double
    ) {
        self.principal = principal
        self.tenorDays = tenorDays
        self.annualRate = annualRate
        self.commissionRate = commissionRate
        self.financingCost = financingCost
        self.commissionAmount = commissionAmount
        self.totalDeductions = totalDeductions
        self.netProceeds = netProceeds
        self.effectiveMonthlyRate = effectiveMonthlyRate
    }
}

// MARK: - Cekten ViewModel

/// Main presentation logic, filtering, and calculation engine coordinator for CektenView.
@MainActor
public final class CektenViewModel: ObservableObject {
    
    // MARK: - Published State
    
    /// Live records fetched from Supabase `cekten_hesabi`
    @Published public var records: [CektenHesap] = []
    
    /// Loading states
    @Published public var isLoading: Bool = false
    @Published public var isRefreshing: Bool = false
    @Published public var errorMessage: String? = nil
    
    /// Filters & Search
    @Published public var selectedStatus: CektenStatusFilter = .all
    @Published public var selectedDateFilter: CektenDateFilter = .all
    @Published public var searchText: String = ""
    
    /// Interactive Simulator Input State
    @Published public var simulatorAmountText: String = "500.000"
    @Published public var simulatorTenorDays: Int = 45
    @Published public var simulatorAnnualRate: Double = 0.45 // 45.0% annual rate
    @Published public var simulatorCommissionRate: Double = 0.01 // 1.0% upfront commission
    @Published public var isSimulatorExpanded: Bool = true
    
    /// Modal & Sheet Presentation
    @Published public var selectedRecordForDetail: CektenHesap? = nil
    @Published public var selectedPaymentRecord: CektenHesap? = nil
    @Published public var isShowingSimulator: Bool = false
    @Published public var isShowingNewRecordSheet: Bool = false
    
    // MARK: - Aliases for View Compatibility
    
    public var selectedFilter: CektenStatusFilter {
        get { selectedStatus }
        set { selectedStatus = newValue }
    }
    
    public var searchQuery: String {
        get { searchText }
        set { searchText = newValue }
    }
    
    public var calcAmount: Double {
        get { parsedSimulatorAmount }
        set {
            let formatter = NumberFormatter()
            formatter.locale = Locale(identifier: "tr_TR")
            formatter.numberStyle = .decimal
            self.simulatorAmountText = formatter.string(from: NSNumber(value: newValue)) ?? "\(Int(newValue))"
        }
    }
    
    public var calcDays: Int {
        get { simulatorTenorDays }
        set { simulatorTenorDays = newValue }
    }
    
    public var calcMonthlyRate: Double {
        get { (simulatorAnnualRate / 12.0) * 100.0 }
        set { simulatorAnnualRate = (newValue * 12.0) / 100.0 }
    }
    
    public var calcAnnualRate: Double {
        simulatorAnnualRate * 100.0
    }
    
    public var calcFinancingCost: Double {
        simulationResult.financingCost
    }
    
    public var calcNetProceeds: Double {
        simulationResult.netProceeds
    }
    
    public var calcEffectiveDiscountRate: Double {
        guard calcAmount > 0 else { return 0.0 }
        return (calcFinancingCost / calcAmount) * 100.0
    }
    
    public var totalFacilityAmount: Double {
        totalPortfolioAmount
    }
    
    public var averageTenorDays: Int {
        Int(round(weightedAverageTenor))
    }
    
    // MARK: - Dependencies
    
    private let service: CektenServiceProtocol
    private let calendar: Calendar
    
    // MARK: - Initialization
    
    public init(
        initialRecords: [CektenHesap] = [],
        service: CektenServiceProtocol = SupabaseService.shared,
        calendar: Calendar = .current
    ) {
        self.records = initialRecords
        self.service = service
        self.calendar = calendar
        
        if initialRecords.isEmpty {
            Task {
                await loadRecords()
            }
        }
    }
    
    public convenience init(
        records: [CektenHesap],
        service: CektenServiceProtocol = SupabaseService.shared
    ) {
        self.init(initialRecords: records, service: service, calendar: .current)
    }
    
    // MARK: - Data Loading Operations
    
    /// Asynchronously fetches records from live Supabase `cekten_hesabi` endpoint.
    public func loadRecords() async {
        guard !isLoading else { return }
        
        isLoading = true
        errorMessage = nil
        
        do {
            let fetched = try await service.fetchCektenRecords()
            self.records = fetched
        } catch {
            self.errorMessage = error.localizedDescription
        }
        
        self.isLoading = false
    }
    
    /// Public alias for loadRecords
    public func loadData() async {
        await loadRecords()
    }
    
    /// Pull-to-refresh execution without blanking existing records.
    public func refreshRecords() async {
        guard !isRefreshing else { return }
        
        isRefreshing = true
        errorMessage = nil
        
        do {
            let fetched = try await service.fetchCektenRecords()
            self.records = fetched
        } catch {
            self.errorMessage = error.localizedDescription
        }
        
        self.isRefreshing = false
    }
    
    /// Public alias for refresh
    public func refresh() async {
        await refreshRecords()
    }
    
    /// Retry operation after failure
    public func retry() async {
        await loadRecords()
    }
    
    /// Dismisses error message
    public func clearError() {
        self.errorMessage = nil
    }
    
    // MARK: - Filter Pipeline
    
    /// Records filtered dynamically by status pill, date preset, and supplier search text.
    public var filteredRecords: [CektenHesap] {
        records.filter { record in
            // 1. Status Filter
            let matchesStatus: Bool
            switch selectedStatus {
            case .all:
                matchesStatus = true
            case .open:
                matchesStatus = record.remainingAmount > 0 && record.status != "Ödendi"
            case .paid:
                matchesStatus = record.remainingAmount <= 0 || record.status == "Ödendi"
            case .partial:
                matchesStatus = record.paidAmount > 0 && record.remainingAmount > 0
            }
            guard matchesStatus else { return false }
            
            // 2. Search Query Filter (Turkish Unicode Case Insensitive)
            let query = searchText.trimmingCharacters(in: .whitespacesAndNewlines)
            if !query.isEmpty {
                let matchesSupplier = record.supplier.localizedCaseInsensitiveContains(query)
                let matchesFacility = record.facilityNo.localizedCaseInsensitiveContains(query)
                let matchesNotes = record.notes?.localizedCaseInsensitiveContains(query) ?? false
                guard matchesSupplier || matchesFacility || matchesNotes else { return false }
            }
            
            // 3. Date Preset Filter
            guard filterRecordByDate(record, filter: selectedDateFilter) else {
                return false
            }
            
            return true
        }
    }
    
    private func filterRecordByDate(_ record: CektenHesap, filter: CektenDateFilter) -> Bool {
        guard filter != .all else { return true }
        guard let recordDate = parseDate(record.date) else { return true }
        
        let now = Date()
        
        switch filter {
        case .all:
            return true
        case .thisMonth:
            return calendar.isDate(recordDate, equalTo: now, toGranularity: .month)
        case .last30Days:
            guard let thirtyDaysAgo = calendar.date(byAdding: .day, value: -30, to: now) else { return true }
            return recordDate >= thirtyDaysAgo && recordDate <= now
        case .future30Days:
            guard let thirtyDaysFuture = calendar.date(byAdding: .day, value: 30, to: now) else { return true }
            return recordDate >= now && recordDate <= thirtyDaysFuture
        }
    }
    
    // MARK: - Portfolio Metrics Engine
    
    /// Sum of total financing amounts across loaded records.
    public var totalPortfolioAmount: Double {
        records.reduce(0.0) { $0 + max(0.0, $1.totalAmount) }
    }
    
    /// Sum of settled / paid amounts across loaded records.
    public var totalPaidAmount: Double {
        records.reduce(0.0) { $0 + max(0.0, $1.paidAmount) }
    }
    
    /// Sum of outstanding balance remaining across loaded records.
    public var totalRemainingAmount: Double {
        records.reduce(0.0) { $0 + max(0.0, $1.remainingAmount) }
    }
    
    /// Amount-weighted average tenor in days.
    public var weightedAverageTenor: Double {
        let validRecords = records.filter { $0.totalAmount > 0 }
        let totalAmt = validRecords.reduce(0.0) { $0 + $1.totalAmount }
        guard totalAmt > 0 else {
            return records.isEmpty ? 0.0 : Double(records.reduce(0) { $0 + $1.tenorDays }) / Double(records.count)
        }
        let weightedSum = validRecords.reduce(0.0) { $0 + ($1.totalAmount * Double($1.tenorDays)) }
        return weightedSum / totalAmt
    }
    
    /// Total financing cost across all records.
    public var totalFinancingCost: Double {
        records.reduce(0.0) { $0 + $1.financingCost }
    }
    
    /// Total net proceeds across all records.
    public var totalNetProceeds: Double {
        records.reduce(0.0) { $0 + $1.netProceeds }
    }
    
    /// Count of open active financing records.
    public var openRecordsCount: Int {
        records.filter { $0.remainingAmount > 0 && $0.status != "Ödendi" }.count
    }
    
    /// Count of settled records.
    public var settledRecordsCount: Int {
        records.filter { $0.remainingAmount <= 0 || $0.status == "Ödendi" }.count
    }
    
    // MARK: - Interactive Cost & Yield Calculation Engine
    
    /// Parses numeric principal amount from user input string.
    public var parsedSimulatorAmount: Double {
        let clean = simulatorAmountText
            .replacingOccurrences(of: ".", with: "")
            .replacingOccurrences(of: ",", with: ".")
            .replacingOccurrences(of: "TL", with: "")
            .replacingOccurrences(of: "₺", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return Double(clean) ?? 0.0
    }
    
    /// Executes the trade finance cost formula:
    /// Cost = Principal * (Tenor / 360) * AnnualRate
    /// Commission = Principal * CommissionRate
    /// Net = Principal - (Cost + Commission)
    public var simulationResult: CektenSimulationResult {
        let principal = max(0.0, parsedSimulatorAmount)
        let tenor = max(1, simulatorTenorDays)
        let rate = max(0.0, simulatorAnnualRate)
        let commRate = max(0.0, simulatorCommissionRate)
        
        let cost = principal * (Double(tenor) / 360.0) * rate
        let commission = principal * commRate
        let totalDeductions = cost + commission
        let net = max(0.0, principal - totalDeductions)
        
        let effectiveMonthly = principal > 0
            ? (totalDeductions / principal) * (30.0 / Double(tenor)) * 100.0
            : 0.0
        
        return CektenSimulationResult(
            principal: principal,
            tenorDays: tenor,
            annualRate: rate,
            commissionRate: commRate,
            financingCost: cost,
            commissionAmount: commission,
            totalDeductions: totalDeductions,
            netProceeds: net,
            effectiveMonthlyRate: effectiveMonthly
        )
    }
    
    /// Presets for calculation simulator
    public func applySimulatorPreset(amount: Double, tenor: Int) {
        let formatter = NumberFormatter()
        formatter.locale = Locale(identifier: "tr_TR")
        formatter.numberStyle = .decimal
        self.simulatorAmountText = formatter.string(from: NSNumber(value: amount)) ?? "\(Int(amount))"
        self.simulatorTenorDays = tenor
    }
    
    // MARK: - Record Settlement & Workflow Actions
    
    /// Records a payment against an active Cekten record optimistically.
    public func recordPayment(for recordId: UUID, paymentAmount: Double) {
        guard let index = records.firstIndex(where: { $0.id == recordId }) else { return }
        var updated = records[index]
        let newPaid = updated.paidAmount + paymentAmount
        let newRemain = max(0.0, updated.totalAmount - newPaid)
        updated.paidAmount = newPaid
        updated.remainingAmount = newRemain
        if newRemain <= 0 {
            updated.status = "Ödendi"
        }
        records[index] = updated
    }
    
    /// Alias for view compatibility
    public func recordPayment(recordId: UUID, paymentAmount: Double) {
        recordPayment(for: recordId, paymentAmount: paymentAmount)
    }
    
    /// Adds new record locally
    public func addNewRecord(supplier: String, amount: Double, dueDate: String, tenor: Int, notes: String?) {
        let newRecord = CektenHesap(
            id: UUID(),
            supplier: supplier,
            totalAmount: amount,
            paidAmount: 0.0,
            remainingAmount: amount,
            interestRate: simulatorAnnualRate,
            tenorDays: tenor,
            status: "Açık",
            dueDate: dueDate,
            date: formatDate(Date()),
            notes: notes
        )
        self.records.insert(newRecord, at: 0)
    }
    
    // MARK: - Formatted Metric Display Helpers
    
    public var formattedTotalPortfolioAmount: String {
        Theme.Formatter.currency(totalPortfolioAmount, showDecimals: true)
    }
    
    public var formattedTotalPaidAmount: String {
        Theme.Formatter.currency(totalPaidAmount, showDecimals: true)
    }
    
    public var formattedTotalRemainingAmount: String {
        Theme.Formatter.currency(totalRemainingAmount, showDecimals: true)
    }
    
    public var formattedWeightedAverageTenor: String {
        String(format: "%.0f Gün", weightedAverageTenor)
    }
    
    public var formattedSimulatorNetProceeds: String {
        Theme.Formatter.currency(simulationResult.netProceeds, showDecimals: true)
    }
    
    public var formattedSimulatorCost: String {
        Theme.Formatter.currency(simulationResult.financingCost, showDecimals: true)
    }
    
    public var formattedSimulatorCommission: String {
        Theme.Formatter.currency(simulationResult.commissionAmount, showDecimals: true)
    }
    
    public var formattedSimulatorTotalDeductions: String {
        Theme.Formatter.currency(simulationResult.totalDeductions, showDecimals: true)
    }
    
    public var formattedEffectiveMonthlyRate: String {
        String(format: "%%%0.2f", simulationResult.effectiveMonthlyRate)
    }
    
    // MARK: - Date Parsing Utilities
    
    private func parseDate(_ dateStr: String) -> Date? {
        let clean = dateStr.components(separatedBy: "T").first ?? dateStr
        
        let isoFormatter = DateFormatter()
        isoFormatter.dateFormat = "yyyy-MM-dd"
        if let d = isoFormatter.date(from: clean) { return d }
        
        let trFormatter = DateFormatter()
        trFormatter.dateFormat = "dd.MM.yyyy"
        return trFormatter.date(from: clean)
    }
    
    public func formatDate(_ dateStr: String) -> String {
        let clean = dateStr.components(separatedBy: "T").first ?? dateStr
        let parts = clean.split(separator: "-")
        if parts.count == 3 {
            return "\(parts[2]).\(parts[1]).\(parts[0])"
        }
        return dateStr
    }
    
    private func formatDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.string(from: date)
    }
}
