//
//  TakasViewModel.swift
//  dars-ios
//
//  Reactive @MainActor ViewModel orchestrating live Supabase data for TakasView.
//  Encapsulates live querying of 8,862 ebs_checks, portfolio KPI calculation,
//  cheque valuation & discounting engine, bank concentration breakdown,
//  and smooth cursor pagination.
//

import SwiftUI
import Combine
import Foundation

// MARK: - Takas Service Protocol

/// Protocol defining backend data requirements for Takas Çekleri Portföyü.
public protocol TakasServiceProtocol: Sendable {
    func fetchChecks(type: CheckType?, status: CheckStatus?, limit: Int, offset: Int) async throws -> [EBSCheck]
}

extension SupabaseService: TakasServiceProtocol {}

// MARK: - Primary Segment Selector

/// Dual segment matching Kuveyt Türk prototype: Takasta vs. İç Takas vs. Ödenen.
public enum TakasSegment: String, CaseIterable, Identifiable, Sendable {
    case takasta = "Takasta"
    case icTakas = "İç Takas"
    case odenen = "Ödenen"
    
    public var id: String { rawValue }
    public var title: String { rawValue }
}

// MARK: - Cheque Status Filter Pills

/// Status filter pills matching Kuveyt Türk design tokens and database enum values.
public enum TakasStatusFilter: String, CaseIterable, Identifiable, Sendable {
    case all = "Tümü"
    case portfoyde = "Portföyde"
    case tahsilde = "Tahsilde"
    case teminatta = "Teminata Verildi"
    case odendi = "Ödendi"
    
    public var id: String { rawValue }
    
    public var targetStatus: CheckStatus? {
        switch self {
        case .all: return nil
        case .portfoyde: return .portfoyde
        case .tahsilde: return .tahsilde
        case .teminatta: return .teminataVerildi
        case .odendi: return .odendi
        }
    }
}

// MARK: - Date Preset Filter

/// Quick date filters for clearing schedules.
public enum TakasDatePreset: String, CaseIterable, Identifiable, Sendable {
    case all = "Tüm Vadeler"
    case today = "Bugün"
    case thisWeek = "Bu Hafta"
    case thisMonth = "Bu Ay"
    case overdue = "Vadesi Geçenler"
    
    public var id: String { rawValue }
}

// MARK: - Bank Concentration Metric

/// Aggregated quota and concentration share per clearing bank.
public struct TakasBankMetric: Identifiable, Equatable, Sendable {
    public var id: String { bankName }
    public let bankName: String
    public let totalAmount: Double
    public let checkCount: Int
    public let concentrationPercentage: Double
    
    public init(bankName: String, totalAmount: Double, checkCount: Int, concentrationPercentage: Double) {
        self.bankName = bankName
        self.totalAmount = totalAmount
        self.checkCount = checkCount
        self.concentrationPercentage = concentrationPercentage
    }
}

// MARK: - Valuation & Discounting Result

/// Result payload generated by the Cheque Valuation Engine.
public struct ChequeValuationResult: Equatable, Sendable {
    public let checkId: UUID
    public let faceValue: Double
    public let dueDate: String
    public let daysToMaturity: Int
    public let monthlyRate: Double
    public let discountRate: Double
    public let grossDiscount: Double
    public let commissionAmount: Double
    public let netPresentValue: Double
    public let effectiveAnnualYield: Double
    
    public init(
        checkId: UUID,
        faceValue: Double,
        dueDate: String,
        daysToMaturity: Int,
        monthlyRate: Double,
        discountRate: Double,
        grossDiscount: Double,
        commissionAmount: Double,
        netPresentValue: Double,
        effectiveAnnualYield: Double
    ) {
        self.checkId = checkId
        self.faceValue = faceValue
        self.dueDate = dueDate
        self.daysToMaturity = daysToMaturity
        self.monthlyRate = monthlyRate
        self.discountRate = discountRate
        self.grossDiscount = grossDiscount
        self.commissionAmount = commissionAmount
        self.netPresentValue = netPresentValue
        self.effectiveAnnualYield = effectiveAnnualYield
    }
}

// MARK: - Portfolio Valuation Summary

/// Consolidated discounting valuation across an entire batch of commercial cheques.
public struct PortfolioValuationSummary: Equatable, Sendable {
    public let totalFaceValue: Double
    public let totalGrossDiscount: Double
    public let totalCommission: Double
    public let netPresentValue: Double
    public let weightedAverageDays: Double
    public let effectiveAverageDiscountRate: Double
    
    public init(
        totalFaceValue: Double,
        totalGrossDiscount: Double,
        totalCommission: Double,
        netPresentValue: Double,
        weightedAverageDays: Double,
        effectiveAverageDiscountRate: Double
    ) {
        self.totalFaceValue = totalFaceValue
        self.totalGrossDiscount = totalGrossDiscount
        self.totalCommission = totalCommission
        self.netPresentValue = netPresentValue
        self.weightedAverageDays = weightedAverageDays
        self.effectiveAverageDiscountRate = effectiveAverageDiscountRate
    }
}

// MARK: - Takas ViewModel

/// Main presentation logic, portfolio analytics, valuation engine, and cursor pagination coordinator for TakasView.
@MainActor
public final class TakasViewModel: ObservableObject {
    
    // MARK: - Published State
    
    /// Accumulated checks fetched from Supabase `ebs_checks`
    @Published public var checks: [EBSCheck] = []
    
    /// Loading & Pagination States
    @Published public var isLoading: Bool = false
    @Published public var isLoadingMore: Bool = false
    @Published public var isRefreshing: Bool = false
    @Published public var canLoadMore: Bool = true
    @Published public var errorMessage: String? = nil
    
    /// Segments & Filter Pills
    @Published public var selectedSegment: TakasSegment = .takasta
    @Published public var selectedStatus: TakasStatusFilter = .all
    @Published public var selectedDatePreset: TakasDatePreset = .all
    @Published public var searchText: String = ""
    
    /// Valuation Engine Parameters
    @Published public var valuationBaseDate: Date = Date()
    @Published public var valuationMonthlyRate: Double = 0.0375 // 3.75% per month (~45% annual)
    @Published public var valuationCommissionRate: Double = 0.005 // 0.5% bank fee
    
    /// Modal Presentation
    @Published public var selectedCheckForAction: EBSCheck? = nil
    @Published public var isShowingValuationSheet: Bool = false
    @Published public var isShowingAddCheckSheet: Bool = false
    @Published public var isShowingMoveBankSheet: Bool = false
    
    // MARK: - Aliases for View Compatibility
    
    public var selectedCheckForDetail: EBSCheck? {
        get { selectedCheckForAction }
        set { selectedCheckForAction = newValue }
    }
    
    public var selectedStatusFilter: TakasStatusFilter {
        get { selectedStatus }
        set { selectedStatus = newValue }
    }
    
    public var searchQuery: String {
        get { searchText }
        set { searchText = newValue }
    }
    
    // MARK: - Pagination Parameters
    
    public let pageSize: Int = 100
    private var currentOffset: Int = 0
    private let service: TakasServiceProtocol
    private let calendar: Calendar
    
    // MARK: - Initialization
    
    public init(
        initialChecks: [EBSCheck] = [],
        service: TakasServiceProtocol = SupabaseService.shared,
        calendar: Calendar = .current
    ) {
        self.checks = initialChecks
        self.service = service
        self.calendar = calendar
        
        if initialChecks.isEmpty {
            Task {
                await loadInitialChecks()
            }
        }
    }
    
    // MARK: - Pagination & Data Loading
    
    /// Loads initial page (0..100) from live Supabase `ebs_checks`.
    public func loadInitialChecks() async {
        guard !isLoading else { return }
        
        isLoading = true
        errorMessage = nil
        currentOffset = 0
        canLoadMore = true
        
        do {
            let fetched = try await service.fetchChecks(
                type: nil,
                status: selectedStatus.targetStatus,
                limit: pageSize,
                offset: currentOffset
            )
            self.checks = fetched
            self.currentOffset = fetched.count
            self.canLoadMore = fetched.count >= pageSize
        } catch {
            self.errorMessage = error.localizedDescription
        }
        
        self.isLoading = false
    }
    
    /// Fetches next page of 100 records and appends to existing dataset without duplicates.
    public func loadMoreChecks() async {
        guard !isLoading, !isLoadingMore, canLoadMore else { return }
        
        isLoadingMore = true
        errorMessage = nil
        
        do {
            let fetched = try await service.fetchChecks(
                type: nil,
                status: selectedStatus.targetStatus,
                limit: pageSize,
                offset: currentOffset
            )
            
            if fetched.isEmpty {
                self.canLoadMore = false
            } else {
                let existingIds = Set(self.checks.map { $0.id })
                let newUnique = fetched.filter { !existingIds.contains($0.id) }
                self.checks.append(contentsOf: newUnique)
                self.currentOffset += fetched.count
                self.canLoadMore = fetched.count >= pageSize
            }
        } catch {
            self.errorMessage = error.localizedDescription
        }
        
        self.isLoadingMore = false
    }
    
    /// Triggers infinite scroll when user scrolls near the end of the loaded list.
    public func loadMoreIfNeeded(currentCheck: EBSCheck) async {
        guard let lastCheck = checks.suffix(5).first else { return }
        if currentCheck.id == lastCheck.id {
            await loadMoreChecks()
        }
    }
    
    /// Pull-to-refresh execution: resets offset to 0 and reloads page 1.
    public func refreshChecks() async {
        guard !isRefreshing else { return }
        
        isRefreshing = true
        errorMessage = nil
        currentOffset = 0
        
        do {
            let fetched = try await service.fetchChecks(
                type: nil,
                status: selectedStatus.targetStatus,
                limit: pageSize,
                offset: 0
            )
            self.checks = fetched
            self.currentOffset = fetched.count
            self.canLoadMore = fetched.count >= pageSize
        } catch {
            self.errorMessage = error.localizedDescription
        }
        
        self.isRefreshing = false
    }
    
    /// Handles status filter pill change by reloading data from backend.
    public func setStatusFilter(_ status: TakasStatusFilter) async {
        guard selectedStatus != status else { return }
        self.selectedStatus = status
        await loadInitialChecks()
    }
    
    /// Public alias for refresh
    public func refresh() async {
        await refreshChecks()
    }
    
    /// Retry operation after failure
    public func retry() async {
        await loadInitialChecks()
    }
    
    /// Dismisses error message
    public func clearError() {
        self.errorMessage = nil
    }
    
    // MARK: - Filter Pipeline
    
    /// Filtered checks combining segmented control, client-side search, and date presets.
    public var filteredChecks: [EBSCheck] {
        checks.filter { check in
            // 1. Segment Filter (Takasta vs. İç Takas vs. Ödenen)
            switch selectedSegment {
            case .takasta:
                if check.isIcTakas { return false }
            case .icTakas:
                if !check.isIcTakas { return false }
            case .odenen:
                let isPaid = check.status.localizedCaseInsensitiveContains("öden") ||
                             check.status.localizedCaseInsensitiveContains("oden")
                if !isPaid { return false }
            }
            
            // 2. Client-side Search Query Filter (Turkish Unicode Case Insensitive)
            let query = searchText.trimmingCharacters(in: .whitespacesAndNewlines)
            if !query.isEmpty {
                let debtor = check.debtor ?? check.drawer
                let creditor = check.creditor ?? ""
                let bank = check.bankName
                let branch = check.branchName
                let checkNo = check.checkNumber
                let matches = debtor.localizedCaseInsensitiveContains(query) ||
                              creditor.localizedCaseInsensitiveContains(query) ||
                              bank.localizedCaseInsensitiveContains(query) ||
                              branch.localizedCaseInsensitiveContains(query) ||
                              checkNo.localizedCaseInsensitiveContains(query)
                guard matches else { return false }
            }
            
            // 3. Date Preset Filter
            guard filterCheckByDate(check, preset: selectedDatePreset) else {
                return false
            }
            
            return true
        }
    }
    
    private func filterCheckByDate(_ check: EBSCheck, preset: TakasDatePreset) -> Bool {
        guard preset != .all else { return true }
        guard let dueDate = parseDate(check.dueDate) else { return true }
        
        let now = Date()
        let startOfToday = calendar.startOfDay(for: now)
        let startOfDue = calendar.startOfDay(for: dueDate)
        
        switch preset {
        case .all:
            return true
        case .today:
            return calendar.isDate(startOfDue, inSameDayAs: startOfToday)
        case .thisWeek:
            return calendar.isDate(startOfDue, equalTo: startOfToday, toGranularity: .weekOfYear)
        case .thisMonth:
            return calendar.isDate(startOfDue, equalTo: startOfToday, toGranularity: .month)
        case .overdue:
            let isPaid = check.status.localizedCaseInsensitiveContains("öden") ||
                         check.status.localizedCaseInsensitiveContains("oden")
            return startOfDue < startOfToday && !isPaid
        }
    }
    
    // MARK: - Portföy Metrics Engine
    
    /// Total monetary face value across currently filtered checks.
    public var totalAmount: Double {
        filteredChecks.reduce(0.0) { $0 + max(0.0, $1.amount) }
    }
    
    /// Total count of checks in active view.
    public var totalCheckCount: Int {
        filteredChecks.count
    }
    
    /// Total face value of cheques sent to bank clearing house ("Tahsilde").
    public var tahsildeAmount: Double {
        filteredChecks
            .filter { $0.status.localizedCaseInsensitiveContains("tahsil") }
            .reduce(0.0) { $0 + $1.amount }
    }
    
    /// Total face value of cheques pledged as loan collateral ("Teminata Verildi").
    public var teminattaAmount: Double {
        filteredChecks
            .filter { $0.status.localizedCaseInsensitiveContains("teminat") }
            .reduce(0.0) { $0 + $1.amount }
    }
    
    /// Total face value of cheques held in corporate safe vault ("Portföyde").
    public var portfoydeAmount: Double {
        filteredChecks
            .filter { $0.status.localizedCaseInsensitiveContains("portföy") || $0.status.localizedCaseInsensitiveContains("portfoy") }
            .reduce(0.0) { $0 + $1.amount }
    }
    
    /// Total face value of matured / collected cheques ("Ödendi").
    public var odendiAmount: Double {
        filteredChecks
            .filter { $0.status.localizedCaseInsensitiveContains("ödendi") || $0.status.localizedCaseInsensitiveContains("odendi") }
            .reduce(0.0) { $0 + $1.amount }
    }
    
    /// Total face value of internal company locked cheques.
    public var icTakasAmount: Double {
        checks
            .filter { $0.isIcTakas }
            .reduce(0.0) { $0 + $1.amount }
    }
    
    /// Amount-weighted average days to maturity from today.
    public var averageTenorDays: Double {
        let activeChecks = filteredChecks.filter { $0.amount > 0 }
        let totalAmt = activeChecks.reduce(0.0) { $0 + $1.amount }
        guard totalAmt > 0 else { return 0.0 }
        
        let now = Date()
        let weightedSum = activeChecks.reduce(0.0) { sum, check in
            let daysLeft = max(0, daysBetween(now, parseDate(check.dueDate) ?? now))
            return sum + (check.amount * Double(daysLeft))
        }
        return weightedSum / totalAmt
    }
    
    /// Bank concentration breakdown aggregated and sorted descending by quota volume.
    public var bankBreakdown: [TakasBankMetric] {
        var bankSums: [String: (amount: Double, count: Int)] = [:]
        
        for check in filteredChecks {
            let bank = check.bankName.trimmingCharacters(in: .whitespacesAndNewlines)
            let key = bank.isEmpty ? "Diğer" : bank
            let current = bankSums[key] ?? (0.0, 0)
            bankSums[key] = (current.amount + check.amount, current.count + 1)
        }
        
        let total = totalAmount
        return bankSums.map { bank, tuple in
            let percentage = total > 0 ? (tuple.amount / total) * 100.0 : 0.0
            return TakasBankMetric(
                bankName: bank,
                totalAmount: tuple.amount,
                checkCount: tuple.count,
                concentrationPercentage: percentage
            )
        }.sorted {
            if abs($0.totalAmount - $1.totalAmount) > 0.001 {
                return $0.totalAmount > $1.totalAmount
            }
            if $0.checkCount != $1.checkCount {
                return $0.checkCount > $1.checkCount
            }
            return $0.bankName < $1.bankName
        }
    }
    
    // MARK: - Valuation & Discounting Engine
    
    /// Calculates net present value and discount charges for a single cheque.
    public func calculateValuation(for check: EBSCheck) -> ChequeValuationResult {
        let principal = max(0.0, check.amount)
        let due = parseDate(check.dueDate) ?? valuationBaseDate
        let rawDays = daysBetween(valuationBaseDate, due)
        let days = max(1, rawDays)
        
        // Monthly Rate: Rate = (Days / 30) * MonthlyRate
        let discountRate = (Double(days) / 30.0) * valuationMonthlyRate
        let grossDiscount = principal * discountRate
        let commission = principal * valuationCommissionRate
        let net = max(0.0, principal - (grossDiscount + commission))
        
        let annualYield = (days > 0 && principal > 0)
            ? (grossDiscount / principal) * (360.0 / Double(days)) * 100.0
            : 0.0
        
        return ChequeValuationResult(
            checkId: check.id,
            faceValue: principal,
            dueDate: check.dueDate,
            daysToMaturity: days,
            monthlyRate: valuationMonthlyRate,
            discountRate: discountRate,
            grossDiscount: grossDiscount,
            commissionAmount: commission,
            netPresentValue: net,
            effectiveAnnualYield: annualYield
        )
    }
    
    /// Calculates consolidated portfolio valuation for a collection of cheques.
    public func calculatePortfolioValuation(for checkList: [EBSCheck]? = nil) -> PortfolioValuationSummary {
        let targetList = checkList ?? filteredChecks
        let activeChecks = targetList.filter { $0.amount > 0 }
        
        var totalPrincipal = 0.0
        var totalDiscount = 0.0
        var totalCommission = 0.0
        var totalNet = 0.0
        var weightedDaysSum = 0.0
        
        for check in activeChecks {
            let res = calculateValuation(for: check)
            totalPrincipal += res.faceValue
            totalDiscount += res.grossDiscount
            totalCommission += res.commissionAmount
            totalNet += res.netPresentValue
            weightedDaysSum += res.faceValue * Double(res.daysToMaturity)
        }
        
        let avgDays = totalPrincipal > 0 ? (weightedDaysSum / totalPrincipal) : 0.0
        let avgRate = totalPrincipal > 0 ? (totalDiscount / totalPrincipal) * 100.0 : 0.0
        
        return PortfolioValuationSummary(
            totalFaceValue: totalPrincipal,
            totalGrossDiscount: totalDiscount,
            totalCommission: totalCommission,
            netPresentValue: totalNet,
            weightedAverageDays: avgDays,
            effectiveAverageDiscountRate: avgRate
        )
    }
    
    // MARK: - Operational Cheque Actions
    
    /// Toggles internal clearing lock (`isIcTakas`) optimistically in local state.
    public func toggleIcTakas(for checkId: UUID) {
        guard let index = checks.firstIndex(where: { $0.id == checkId }) else { return }
        var updated = checks[index]
        updated.isIcTakas.toggle()
        if updated.isIcTakas {
            updated.status = "İç Takas"
        } else {
            updated.status = "Tahsilde"
        }
        checks[index] = updated
    }
    
    /// Routes cheque to a destination clearing bank.
    public func moveCheckToBank(checkId: UUID, destinationBank: String) {
        guard let index = checks.firstIndex(where: { $0.id == checkId }) else { return }
        var updated = checks[index]
        updated.bankName = destinationBank
        checks[index] = updated
    }
    
    /// Marks cheque as collected / paid.
    public func markCheckAsCollected(checkId: UUID) {
        guard let index = checks.firstIndex(where: { $0.id == checkId }) else { return }
        var updated = checks[index]
        updated.status = "Ödendi"
        checks[index] = updated
    }
    
    // MARK: - Formatted Display Properties
    
    public var formattedTotalAmount: String {
        Theme.Formatter.currency(totalAmount, showDecimals: true)
    }
    
    public var formattedTahsildeAmount: String {
        Theme.Formatter.currency(tahsildeAmount, showDecimals: true)
    }
    
    public var formattedTeminattaAmount: String {
        Theme.Formatter.currency(teminattaAmount, showDecimals: true)
    }
    
    public var formattedPortfoydeAmount: String {
        Theme.Formatter.currency(portfoydeAmount, showDecimals: true)
    }
    
    public var formattedOdendiAmount: String {
        Theme.Formatter.currency(odendiAmount, showDecimals: true)
    }
    
    public var formattedIcTakasAmount: String {
        Theme.Formatter.currency(icTakasAmount, showDecimals: true)
    }
    
    public var formattedAverageTenor: String {
        String(format: "%.0f Gün", averageTenorDays)
    }
    
    // MARK: - Date Helpers
    
    private func parseDate(_ dateStr: String) -> Date? {
        let clean = dateStr.components(separatedBy: "T").first ?? dateStr
        
        let isoFormatter = DateFormatter()
        isoFormatter.dateFormat = "yyyy-MM-dd"
        if let d = isoFormatter.date(from: clean) { return d }
        
        let trFormatter = DateFormatter()
        trFormatter.dateFormat = "dd.MM.yyyy"
        return trFormatter.date(from: clean)
    }
    
    public func formatDate(_ dateStr: String) -> String {
        let clean = dateStr.components(separatedBy: "T").first ?? dateStr
        let parts = clean.split(separator: "-")
        if parts.count == 3 {
            return "\(parts[2]).\(parts[1]).\(parts[0])"
        }
        return dateStr
    }
    
    public func daysBetween(_ start: Date, _ end: Date) -> Int {
        let startDay = calendar.startOfDay(for: start)
        let endDay = calendar.startOfDay(for: end)
        return calendar.dateComponents([.day], from: startDay, to: endDay).day ?? 0
    }
    
    public func daysRemainingBadge(for dueDateStr: String) -> (text: String, isOverdue: Bool) {
        guard let due = parseDate(dueDateStr) else { return ("—", false) }
        let diff = daysBetween(Date(), due)
        if diff < 0 {
            return ("\(abs(diff)) Gün Geçti", true)
        } else if diff == 0 {
            return ("Bugün", false)
        } else {
            return ("\(diff) Gün Kaldı", false)
        }
    }
}
