import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRight, CircleDollarSign, Pencil, Plus, Search, Trash2, Waypoints } from 'lucide-react';
import { PageHeader } from '../../components/ui/PageHeader';
import { Modal } from '../../components/ui/Modal';
import { ModuleFileActions } from '../../components/ui/ModuleFileActions';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../lib/auth';
import { useToast } from '../../lib/toast';
import { useVehicles } from './store';

type PaymentStatus='bekliyor'|'odendi'|'itiraz';
interface Passage{id:string;vehicle_id:string;passage_date:string;entry_point:string;exit_point:string;amount:number;hgs_account:string;payment_status:PaymentStatus;description:string|null}
interface FormState{vehicleId:string;passageDate:string;entryPoint:string;exitPoint:string;amount:string;hgsAccount:string;paymentStatus:PaymentStatus;description:string}
const emptyForm=():FormState=>({vehicleId:'',passageDate:new Date().toISOString().slice(0,16),entryPoint:'',exitPoint:'',amount:'',hgsAccount:'',paymentStatus:'bekliyor',description:''});
const statusLabel:Record<PaymentStatus,string>={bekliyor:'Bekliyor',odendi:'Ödendi',itiraz:'İtiraz'};
const statusClass:Record<PaymentStatus,string>={bekliyor:'bg-amber-50 text-amber-700',odendi:'bg-emerald-50 text-emerald-700',itiraz:'bg-red-50 text-red-700'};
const money=(value:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(value);

export function HgsPassagesPage(){
  const {user}=useAuth();const{notify}=useToast();const{vehicles}=useVehicles();
  const [items,setItems]=useState<Passage[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');
  const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Passage>();const[form,setForm]=useState<FormState>(emptyForm());const[saving,setSaving]=useState(false);
  const canWrite=['Yönetici','Muhasebe','Finans'].includes(user?.role??'');
  const refresh=useCallback(async()=>{if(!user?.organizationId)return;setLoading(true);const{data,error}=await supabase.from('hgs_passages').select('*').eq('organization_id',user.organizationId).order('passage_date',{ascending:false});if(error)notify(error.message,'error');else setItems((data??[]).map(x=>({...x,amount:Number(x.amount)})) as Passage[]);setLoading(false)},[user?.organizationId,notify]);
  useEffect(()=>{void refresh()},[refresh]);
  const filtered=useMemo(()=>items.filter(x=>{const vehicle=vehicles.find(v=>v.id===x.vehicle_id);return`${vehicle?.plate??''} ${x.entry_point} ${x.exit_point} ${x.hgs_account}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'))}),[items,vehicles,query]);
  const openForm=(item?:Passage)=>{setEditing(item);setForm(item?{vehicleId:item.vehicle_id,passageDate:item.passage_date.slice(0,16),entryPoint:item.entry_point,exitPoint:item.exit_point,amount:String(item.amount),hgsAccount:item.hgs_account,paymentStatus:item.payment_status,description:item.description??''}:{...emptyForm(),vehicleId:vehicles[0]?.id??''});setOpen(true)};
  const save=async()=>{if(!user?.organizationId||!form.vehicleId||!form.passageDate||!form.entryPoint.trim()||!form.exitPoint.trim()||Number(form.amount)<0){notify('Araç, tarih, giriş, çıkış ve geçerli tutar zorunludur.','error');return}setSaving(true);const payload={organization_id:user.organizationId,vehicle_id:form.vehicleId,passage_date:new Date(form.passageDate).toISOString(),entry_point:form.entryPoint.trim(),exit_point:form.exitPoint.trim(),amount:Number(form.amount)||0,hgs_account:form.hgsAccount.trim(),payment_status:form.paymentStatus,description:form.description.trim()||null,updated_at:new Date().toISOString()};const result=editing?await supabase.from('hgs_passages').update(payload).eq('id',editing.id).eq('organization_id',user.organizationId):await supabase.from('hgs_passages').insert(payload);setSaving(false);if(result.error){notify(result.error.message,'error');return}notify(editing?'HGS geçişi güncellendi.':'HGS geçişi eklendi.','success');setOpen(false);await refresh()};
  const remove=async(item:Passage)=>{if(!confirm('Bu HGS geçişi silinsin mi?'))return;const{error}=await supabase.from('hgs_passages').delete().eq('id',item.id).eq('organization_id',user?.organizationId);if(error)notify(error.message,'error');else{notify('HGS geçişi silindi.','success');await refresh()}};
  const total=items.reduce((sum,x)=>sum+x.amount,0),pending=items.filter(x=>x.payment_status==='bekliyor').reduce((sum,x)=>sum+x.amount,0);
  return <div className="mx-auto max-w-7xl"><PageHeader title="HGS - Geçiş" description="Araçların otoyol ve köprü geçişlerini, tutarlarını ve ödeme durumlarını yönetin." actions={<><ModuleFileActions module="vehicles" exportName="hgs-gecisleri" uploadEnabled={false} rows={items.map(x=>({Araç:vehicles.find(v=>v.id===x.vehicle_id)?.plate,Tarih:x.passage_date,Giriş:x.entry_point,Çıkış:x.exit_point,Tutar:x.amount,'HGS Hesabı':x.hgs_account,Durum:statusLabel[x.payment_status]}))}/>{canWrite&&<button className="btn-primary" onClick={()=>openForm()}><Plus size={16}/>Geçiş Ekle</button>}</>}/>
    <div className="mb-5 grid gap-4 sm:grid-cols-3"><Metric icon={<Waypoints size={16}/>} value={String(items.length)} label="Toplam Geçiş"/><Metric icon={<CircleDollarSign size={16}/>} value={money(total)} label="Toplam Tutar"/><Metric icon={<CircleDollarSign size={16}/>} value={money(pending)} label="Bekleyen Tutar"/></div>
    <div className="relative mb-4 max-w-lg"><Search size={16} className="absolute left-3 top-3 text-gray-400"/><input className="input pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Plaka, giriş, çıkış veya HGS hesabı ara..."/></div>
    <div className="card overflow-x-auto"><table className="min-w-full"><thead><tr><th className="table-th">Tarih</th><th className="table-th">Araç</th><th className="table-th">Güzergâh</th><th className="table-th">HGS Hesabı</th><th className="table-th">Tutar</th><th className="table-th">Durum</th><th className="table-th"></th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="table-td py-12 text-center text-gray-400">Geçişler yükleniyor...</td></tr>:filtered.length===0?<tr><td colSpan={7} className="table-td py-12 text-center text-gray-400">HGS geçişi bulunamadı.</td></tr>:filtered.map(x=><tr key={x.id} className="border-t border-gray-100"><td className="table-td">{new Date(x.passage_date).toLocaleString('tr-TR',{dateStyle:'short',timeStyle:'short'})}</td><td className="table-td font-medium">{vehicles.find(v=>v.id===x.vehicle_id)?.plate??'—'}</td><td className="table-td"><span>{x.entry_point}</span><ArrowRight size={13} className="mx-2 inline text-gray-400"/><span>{x.exit_point}</span></td><td className="table-td">{x.hgs_account||'—'}</td><td className="table-td font-medium">{money(x.amount)}</td><td className="table-td"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusClass[x.payment_status]}`}>{statusLabel[x.payment_status]}</span></td><td className="table-td">{canWrite&&<div className="flex gap-2"><button className="text-gray-500 hover:text-brand-600" onClick={()=>openForm(x)} aria-label="Düzenle"><Pencil size={16}/></button><button className="text-gray-400 hover:text-red-600" onClick={()=>void remove(x)} aria-label="Sil"><Trash2 size={16}/></button></div>}</td></tr>)}</tbody></table></div>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?'HGS Geçişini Düzenle':'Yeni HGS Geçişi'}><div className="grid gap-4 sm:grid-cols-2"><Field label="Araç"><select className="input" value={form.vehicleId} onChange={e=>setForm({...form,vehicleId:e.target.value})}><option value="">Araç seçin</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.plate} · {v.brand} {v.model}</option>)}</select></Field><Field label="Geçiş Tarihi"><input className="input" type="datetime-local" value={form.passageDate} onChange={e=>setForm({...form,passageDate:e.target.value})}/></Field><Field label="Giriş Noktası"><input className="input" value={form.entryPoint} onChange={e=>setForm({...form,entryPoint:e.target.value})}/></Field><Field label="Çıkış Noktası"><input className="input" value={form.exitPoint} onChange={e=>setForm({...form,exitPoint:e.target.value})}/></Field><Field label="Tutar"><input className="input" type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="HGS Hesabı / Etiket"><input className="input" value={form.hgsAccount} onChange={e=>setForm({...form,hgsAccount:e.target.value})}/></Field><Field label="Ödeme Durumu"><select className="input" value={form.paymentStatus} onChange={e=>setForm({...form,paymentStatus:e.target.value as PaymentStatus})}>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Açıklama" wide><textarea className="input min-h-20" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><button className="btn-primary sm:col-span-2" disabled={saving} onClick={()=>void save()}>{saving?'Kaydediliyor...':'Kaydet'}</button></div></Modal>
  </div>
}
function Metric({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="card p-4"><div className="mb-3 flex h-8 w-8 items-center justify-center rounded-lg bg-gray-50 text-gray-500">{icon}</div><div className="text-xl font-semibold">{value}</div><div className="text-xs text-gray-500">{label}</div></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?'sm:col-span-2':''}><span className="label">{label}</span>{children}</label>}
