name: dars-ios
options:
  bundleIdPrefix: com.amasyaetas
  deploymentTarget:
    iOS: "17.0"
  defaultConfig: Release

settings:
  base:
    DEVELOPMENT_TEAM: WGARWL7QZ4

packages:
  supabase-swift:
    url: https://github.com/supabase/supabase-swift.git
    from: "2.5.0"

targets:
  dars-ios:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: dars-ios
        excludes:
          - "**/*.md"
          - "Tests/**"
    dependencies:
      - package: supabase-swift
        product: Supabase
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amasyaetas.mobile
        PRODUCT_NAME: "dars-ios"
        DEVELOPMENT_TEAM: WGARWL7QZ4
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: dars-ios/App/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Manual
        PROVISIONING_PROFILE_SPECIFIER: "EtasEt_AppStore_Profile"
        CODE_SIGN_IDENTITY: "Apple Distribution"
        ENABLE_BITCODE: NO
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "55"
        VERSIONING_SYSTEM: "apple-generic"

  dars-iosTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: dars-ios/Tests
    dependencies:
      - target: dars-ios
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amasyaetas.mobileTests
        DEVELOPMENT_TEAM: WGARWL7QZ4
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"



