name: MarifEt
options:
  bundleIdPrefix: com.amasyaetas
  deploymentTarget:
    iOS: "16.0"
  defaultConfig: Release
targets:
  MarifEt:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.amasyaetas.mobile
        PRODUCT_NAME: MarifEt
        DEVELOPMENT_TEAM: WGARWL7QZ4
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "EtasEt_AppStore_Profile"
        ENABLE_BITCODE: NO
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "2"
