name: Deploy iOS App to TestFlight

on:
  push:
    paths:
      - 'ios/**'
      - '.github/workflows/deploy_ios.yml'
    branches: [ main, master ]
  workflow_dispatch:

env:
  FASTLANE_SKIP_UPDATE_CHECK: "true"
  FASTLANE_HIDE_CHANGELOG: "true"
  FASTLANE_DISABLE_ANIMATION: "true"
  CI: "true"

jobs:
  build-and-upload:
    name: Build & Upload to Apple TestFlight
    runs-on: macos-15

    defaults:
      run:
        working-directory: ios

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Install Apple Certificate and Provisioning Profile
        run: |
          # Import certificate to the default login keychain
          security import certs/ios_distribution.p12 -P "Apple123!" -A -t cert -f pkcs12 -k ~/Library/Keychains/login.keychain-db
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" ~/Library/Keychains/login.keychain-db

          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp certs/EtasEt_AppStore_Profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Run Fastlane Beta
        run: |
          fastlane ios beta
