name: Deploy iOS App to TestFlight

on:
  push:
    paths:
      - 'ios/**'
      - '.github/workflows/deploy_ios.yml'
    branches: [ main, master ]
  workflow_dispatch:

env:
  FASTLANE_SKIP_UPDATE_CHECK: "true"
  FASTLANE_HIDE_CHANGELOG: "true"
  FASTLANE_DISABLE_ANIMATION: "true"
  CI: "true"

jobs:
  build-and-upload:
    name: Build & Upload to Apple TestFlight
    runs-on: macos-15

    defaults:
      run:
        working-directory: ios

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Install Apple Certificate and Provisioning Profile
        run: |
          KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain
          KEYCHAIN_PASSWORD=empty
          
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # Import certificate
          security import certs/ios_distribution.p12 -k $KEYCHAIN_PATH -P 'Apple123!' -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # Add to keychain search list without overriding existing keychains
          security list-keychains -d user -s $KEYCHAIN_PATH $(security list-keychains -d user | tr -d '"')

          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp certs/EtasEt_AppStore_Profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Run Fastlane Beta
        run: |
          fastlane ios beta
